### ISSUE TITLE
Update a field of a content entry

### ISSUE THREAD

**Issue by nicsunboy** [locomotivecms/engine#1035]
I created a content type called "posts" with a field called "views" which is integer. The field "views" are supposed to add 1 incrementally every time the content entry page was visited. 
I try {% assign post.views = post.views +1 %} in liquid ,but that didn't make sense. 
Is there any liquid tag to carry it out ?

**Comment by manuchap** [comment]
The only way you can interact from the front-end is via public submission which must be enabled on a model (originally designed for a contact form).
You'd have to create a views model that belongs to your posts model, get the value, add one and post it back in from hidden inputs. A bit cumbersome I reckon. I didn't bother actually trying this since the issue is closed...

**Comment by nicsunboy** [comment]
@manuchap, Add a gem called locomotive liquid extension, that can do that.
