### ISSUE TITLE
Upgrade to mongoid 5 before release to support SCRAM-SHA-1

### ISSUE THREAD

**Issue by goodwill** [locomotivecms/engine#1061]
I think this is important given the recent effort for the mongodb hosting providers to depreciate CR in favour of SCRAM-SHA-1. Indeed on heroku by default I don't think you have access to mongodb 2.6 anymore, so to make sure locomotivecms is future proof I think this is very high priority.

**Comment by did** [comment]
hi @goodwill, that's absolutely right. Mongolab, for instance, doesn't offer Mongodb 2.6 databases in their free plan anymore. This also means there is no way to install a free Locomotive v3 instance on Heroku for now.

Now about upgrading to Mongoid 5. The thing is that we can't upgrade because they've got (blocking) issues breaking our specs. 

- the blocking issue: https://jira.mongodb.org/browse/MONGOID-4159
- the status on the Mongoid 5 migration: https://trello.com/c/achbxT8J/83-mongoid-upgrade-to-mongoid-5-0

**Comment by manuchap** [comment]
I'm not technical enough to assert this but it seems to me that hosting providers who propose mongodb along with other technologies tend to postpone updating mongod since the implementation of gridfs. I believe the curlpit resides in the difficulty to avoid using this protocol as a kinda of torrent-like doorway (as in reopen megaupload ;-). Hopefully I'm totally wrong (and a bit paranoid). Any idea on this?

**Comment by rvalyi** [comment]
note: the fix has been released in mongoid

**Comment by did** [comment]
@rvalyi thanks :-) I'm working on it right now. All the tests pass. I need to run some integration tests now. We're getting close :-)

**Comment by rvalyi** [comment]
@did thanks. In fact I could hack Dokku to test Locomotive on Mongo server 3 already fortunately. That being said I'll still answer your email. We just decided I'll work some 40 days to build a full blown open source e-commerce with LocomotiveCMS in the Frontend, Odoo in the backend and a Solr cached catalog. I'll update you soon, the potential is huge.

**Comment by did** [comment]
hey @rvalyi, no worries :-) That sounds super exciting! 

[UPDATE] Steam is now using the official ruby Mongo driver (https://github.com/locomotivecms/steam/commit/d24d5d356ceb296f3e3731bafdf828445856795b).

**Comment by did** [comment]
https://github.com/locomotivecms/engine/commit/43a88c2a47877d163c465037bc23865df8c17e50 should fix this problem :-)

**Comment by rvalyi** [comment]
@did thanks! I'll test in the very next days. That's cool as it will allow us to run our production new corporate website on MongoDB 3 directly...
