### ISSUE TITLE
Greek locale

### ISSUE THREAD

**Issue by billp** [locomotivecms/engine#1096]
[greek_translations.zip](https://github.com/locomotivecms/engine/files/69043/greek_translations.zip)

Hello, I've made the Greek translations based on "en" locale but I was not able to insert a new option on account settings. Can you give me a hint for how to do it?

**Comment by did** [comment]
hi @billp, that's awesome! 
Actually, could you use https://www.transifex.com/locomotive/locomotive-engine to merge your translations?
To answer your initial question, in order to to enable your locale in the back-office, add your locale in the config/locomotive.rb file in your main Rails app embedding the Locomotive engine (https://github.com/locomotivecms/engine/blob/master/lib/generators/locomotive/install/templates/locomotive.rb#L18). 
Again thanks!

**Comment by billp** [comment]
Thanks, I will do it soon :)

**Comment by did** [comment]
thanks @billp ;-)
