### ISSUE TITLE
FR: alternative cloud storages support

### ISSUE THREAD

**Issue by craft37** [locomotivecms/engine#1104]
Could you include supporting services like cloud.google.com, heroku-based or even custom ones alongside with S3 ?
S3 just redundant and expensive for small projects.
Thank you!

**Comment by anong** [comment]
Agree! If support unload files ( images, videos, ... ) from google drive or flickr, will be a killer feature!

**Comment by did** [comment]
@craft37 We should write a guide about that because it's fairly easy since we rely on the carrierwave component for the upload functionality. And guess what? https://github.com/carrierwaveuploader/carrierwave#using-google-storage-for-developers ;-) 
So, it's just a matter of adapting the **config/initializers/carrierwave.rb** file of your rails app!

@anong I've been discussing about that with @nielsenramon. That's part of the next features.
