### ISSUE TITLE
Should not show same prompt for saving as for cancel action in back-office

### ISSUE THREAD

**Issue by MonteHeidy** [locomotivecms/engine#1188]
Currently upon saving changes in back office the user gets the same prompt as for cancel action.

**Example**
- Open a page in back office
- Add text in one of the wysiwyg editors
- Hit save button
- Prompt is shown asking whether user wants to leave the website, including the hint that changes may not be saved.
- Can hit "stay" or "leave" - Confusion - which one to press?
- Press "leave"
  - changes are saved --> That feels wrong, as the prompt suggested to me that my changes may be lost.
- Press "stay"  
  - Page stays in "saving-state" (showing spinner on button etc). 
  - Upon cancelling to exit the state, changes are not being saved.

Presumably this is a follow-up issue of #1130

**Comment by did** [comment]
hi @MonteHeidy, sorry for the delay.
So, first, as long as you hit the save button, you should be okay to leave the page without being asked for anything.  At least, that's the expected behaviour in the last version. If that's not the case for you, then you've to check if there was a JS error in your browser console (+ give me the browser you used + its version and your OS).
Regarding the message displayed when you're leaving the page, some browsers force displaying their own message and discard the one we defined in Locomotive. There is little we can do about that.

**Comment by MonteHeidy** [comment]
@did Fixed in latest version. Error does not occur anymore.
