### ISSUE TITLE
Validation errors on redirect_url

### ISSUE THREAD

**Issue by merqlove** [locomotivecms/engine#1195]
Incompatible with localize validation. Seems that validator runs on every value (yes, on blank too)
I have added custom REGEX & dropped check for persistence. Anyway it blank by default.
https://github.com/merqlove/engine/commit/6613a79f7667e01d27737a63a7ff8d08682bd70f

**Comment by did** [comment]
hey @merqlove this one is tricky.The case you're describing in when you create a page in 2 languages and finally decide that it will be a redirect page. The thing is that because you posted your form, it filled a blank redirect_url in all the locales. Then, it becomes impossible to modify the redirect_url. 

By default, Mongoid validates the attributes of a model in all the locales https://github.com/mongodb/mongoid/blob/master/lib/mongoid/validatable/presence.rb#L31.

I don't feel good to modify the Mongoid behavior and your patch lets editors to enter a blank redirect_url which is not acceptable.

Let me see if I can come up with a good solution.

**Comment by merqlove** [comment]
Yeah, i c :)
Ok, i will keep it as workaround locally till better solution.

**Comment by did** [comment]
@menkel check out my commit https://github.com/locomotivecms/engine/commit/51329bb7ad973b75eef7fdecef6830366dd0d8e1, it's working great.
