### ISSUE TITLE
SEO friendly urls and balanced site treemap

### ISSUE THREAD

**Issue by youleaf** [locomotivecms/engine#1225]
Given a content type (let's say :products) in which each item is related to a category (let's say :category), we want to achieve this:

/:category (list all products belonging to :category)
/:category/:product (product page)

This kind of site tree structure is considered the best practice under a SEO perspective (see also 
 https://blog.kissmetrics.com/site-structure-enhance-seo/ for more details) and we would love to be able to implent it using our favorite cms.

**Comment by toreyheinz** [comment]
Assuming this is possible, you'd want to ensure the product is only accessible via a single URL or set up a canonical URL tag.

You don't want the same product page at different URLs: /products/t-shirt, /products/rails/t-shirt, and /products/ruby/t-shirt, which would create a duplicate content issue.

Couple options for this:

- (hard, but would be the best) Redirect to a product's category URL, if there is more than one category redirect to the first.
- (easy, and probably just fine) Add a canonical URL tag to the product page, and set it the /products/t-shirt URL. [Moz Article](https://moz.com/blog/canonical-url-tag-the-most-important-advancement-in-seo-practices-since-sitemaps)

**Comment by youleaf** [comment]
@toreyheinz: Definitely:  when using the url schema /:category/:product and a "many_to_many" relationship between :categories and :products, multiple urls for the same product will exist. I think the canonical URL is what is commonly used in this scenario. Probably also the auto-generated sitemap.xml should take this into account.

If you sell just shirts, an ideal "_shallow website_" url schema should be like this:

```
/
/rails
  /rails/t-shirt
/ruby
  /ruby/mug 
```

In locomotive, you could achieve this creating a content_type for "rails" products and another one for "ruby" products. But creating one content_type per category sounds weird if all the entities are products, have identical attributes and the same content_type would do...

**Comment by did** [comment]
what about using https://doc.locomotivecms.com/v4.0/docs/custom-routes?
