### ISSUE TITLE
Templatized Page using External data

### ISSUE THREAD

**Issue by ghost** [locomotivecms/engine#123]
Maybe I am the only person in the world who needs this, but I have a customer who has an external system they manage inventory in. I can pull a JSON file from there with all the product information. What I am needing is a way to display that on the site. 

I am able to use the "consume" tag to get a list of everything. But what I am trying to do now is create a show page for an individual listing out of the feed. 

So for example you could have:

/plans which makes a call to some-external-service.com/plans.json to return a list of plans and show them to a client. 

What I would then wont is a way to have a link to (assuming a plan in the json has a slug of small): 

/plans/small which would call some-external-service.com/plans/small.json to load the resource. If that slug doesn't exists then return a 404, if that external service times ou then a way to display that it is unavailable at this time. 

I had two real thoughts on how to implement this. 1) Allow a page to have an external template which gets a url of something like http://some-external-service.com/plans/{{slug}}.json, or creating a new model that is an external model which just loads the http://some-external-service.com/plans.json (which would need all of the data in it to show the listing) and can cache that for faster lookups. 

I like each option for different reasons, but wanted to get some other opinions on it before I try to create something I submit a pull request for.

**Comment by youleaf** [comment]
Pretty url support for external data would be great and would add a lot of power to locomotive. At the moment we are facing this problem on multiple sites. Until now, we adopted the following solutions:
1) map resources in the database, creating a model coupling pretty urls (slugs) with external ids
2) mount an external app implementing pretty urls under a given route
3) lots of url rewrite rules

2) and 3) are really hard to mantain. 1) is not always possible, in particular if data are going to change often or dynamically.

In some cases we are now implementing @did's solution using url params (`/resource?id=resource_identifier`). The limit is that under a SEO point of view, this is not so good.

Basically, having (at the route level) something like
`/resource/:resource_identifier`
mapped to 
`{{ params.resource_identifier }}` 
in the template would make the trick. This could be the simplest solution.


A more complex solution would be to use httparty (just like in 'consume' tag) to do the coupling, creating a new kind of template accessing remote data instead of a local locomotive model. Such a template would access a remote resource just like a model, configuring via admin a url containing  one param and passing the returning object to the view.

For example, we could create a page accessing github repositories for a given user creating a _remote model_ called 'repos', defining a url like:
`https://api.github.com/users/{{value}}/repos`

{{value}} is a placeholder for the string to be replaced with the param passed in the url. In this way, when a user visits the url

`/repos/locomotivecms`

httparty calls the url `https://api.github.com/users/locomotivecms/repos` and the template receives the {{repos}} object, containing the response of the api call defined above with the :param value replaced.
Once the repos object is in the view, it could be used as a normal object - and more complex API behaviours could be achieved by using more 'consume' tag in the page itself.

If the {{value}} is seo-friendly (like in the example), this would also produce a seo-friendly url.

I'd like to be able to produce a POC of this, but a deep knowledge of locomotive internals would be needed and unfortunately in this moment I can't dive into it. 

just my 2 cents!

**Comment by did** [comment]
related issues/features #811, #125

**Comment by did** [comment]
Custom routes as described [here](https://doc.locomotivecms.com/v4.0/docs/custom-routes) solves this problem.
Details about the implementation can be found [here](https://github.com/locomotivecms/steam/commit/5902ef2f67f797828fe19f6aec279c777b0f3b2d)
