### ISSUE TITLE
Move render_activity_sentence into Activity model

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1287]
I was trying to create a status page for my sites and wanted to display some activity similar to the dashboard site activity log. 

The current [Activity model](https://github.com/locomotivecms/engine/blob/master/app/models/locomotive/activity.rb) is rather sparse in terms of available methods making it difficult to extract usable info from. I dug into it and found out that most of the logic for extracting activity info is within the [DashboardHelper#render_activity_sentence](https://github.com/locomotivecms/engine/blob/master/app/helpers/locomotive/dashboard_helper.rb#L30) making it difficult for me to integrate with my solution.

Could we not move the `render_activity_sentence` method into the model somehow?

**Comment by did** [comment]
```
I was trying to create a status page for my sites and wanted to display some activity similar to the dashboard site activity log.
```
What kind of extra events are you going to track? Or do you just want a page in the CMS to display all the activities for your sites? Do you have a mockup?

Now, speaking of the implementation. I'd rather keep the model super light. 
I also took a look the current implementation. Since we need to call Rails url helpers + DOM helpers, it makes totally sense to use a Rails helper.

Now, if you tell me that we need those methods for another view (within a different controller), I guess we've to move the code related to the display of the activities into its own helper, like Locomotive::ActivityHelper.

How does it sound to you?

**Comment by westonganger** [comment]
I originally thought it could be extracted to the model, however after trying a solution I realize the method is fairly tied to the view. 

Yes it would be helpful and more intuitive to extract it to its own helper I would think. Thanks.
