### ISSUE TITLE
Backend fields not showing for editable_* methods

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1308]
I cant seem to find the backend field for any editable_* methods. Where are they supposed to appear. I assume under Content tab somewhere.

```html
---
title: Features
handle: features
seo_title: Features
---
{% extends "layouts/default" %}

{% block main %}
  <header class="header-primary">
    <div class="grid grid-centered">
      <div class="grid-cell">
        {% block header %}
        <div class="header-content is-small">
          <h1>{% editable_text "headline", format: raw, rows: 1 %}Our features{% endeditable_text %}</h1>
          <p>
            {% editable_text "tagline", format: raw, rows: 3 %}
            Focus on what matters: front-end technology, standard development process and no learning time for your client.
            {% endeditable_text %}
          </p>
        </div>
        {% endblock %}
      </div>
    </div>
  </header>

  ... snipped ....
{% endblock %}
```

![Screenshot from 2019-05-16 16-57-43](https://user-images.githubusercontent.com/3414795/57894487-fd333900-77fb-11e9-904c-515a3049e6b9.png)

**Comment by westonganger** [comment]
I found the editable elements edit page within `/locomotive/<my-site>/pages/<my-page-id>/editable_elements`. Where is the navigational link/button to get to this page though?

**Comment by did** [comment]
Very good question. You can't use editable_elements and sections at the same time. 
Editable_elements are very handy but when you've got more a lot of elements inside page, the UI gets super difficult to use. Sections help to organize this. 
Of course, we thought about having the 2 in the same UI but it was complicated to design something easy to use. Moreover, sections are so much powerful that we only use sections now.

**Comment by westonganger** [comment]
I was really fascinated by the complete simplicity of the editable_elements feature when considering the Locomotive platform. Basically it was a selling point. So while sections may be a better idea in most cases, I would much prefer that this option be left up to the developer of the site. 

Could we please include this as a tab. Do not show the tab if there are no editable_elements and show it if there is.

**Comment by did** [comment]
We really don't want to have sections and editable elements at the same time in a site.
That's why when we detect that you're using sections (so basically, new v4 sites), we display the new editor UI. 
That being said, if you choose to only use editable elements, we'll display the old editor UI.

Unfortunately, for UX and UI, we can't show both UI. Even displaying a link to the editable elements will break the UI (not enough space in the tabs). Besides, it will break the navigation in the editor UI (when you visit another page inside the editor). And I don't talk about the ways Sections and Editable elements refresh the content of the page. 
Last argument, end users won't understand what the difference is between those 2 kind of content.

**Comment by westonganger** [comment]
Ok fine if you absolutely think you do not want them then I would appreciate an error if both editable_elements and sections are mixed in a page. Also I would like this information

**Comment by westonganger** [comment]
It appears the following error occurs if editable_elements and sections are mixed within a **site**

```
[my-page] You can't use editable elements whereas you declared section(s)
```

For backwards compatibility, it would be better if it only restricted to editable_elements and sections are mixed within a **page**
