### ISSUE TITLE
Add support for default value within `settings` key

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1316]
Similar to #1298 

Can we add support for the default value within the `settings` key of Section definition. This makes it much simpler by avoiding any inconsistencies caused by having seperate `default` and `settings` keys.

**Comment by westonganger** [comment]
Also please make it deployable I note that this new sample field will not be deployed? Can we please make it deployable so that it is a complete drop in replacement for config/site.yml metafields. For backwards compatibility, you could make the config/site.yml the 1st choice and then the sample value the second choice.

**Comment by westonganger** [comment]
This feature I am asking for here actually appears to be documented here:

https://doc.locomotivecms.com/v4.0/docs/json-definition#section-settings

However it does not seem to work for me.

**Comment by did** [comment]
The `default` attribute is misleading and the document is not accurate. If I remember correctly, the default attribute is **only** used when it's included to the settings of a block. 
So when you add a new block in your editor UI, we'll use the default values so that your block doesn't appear empty.

Anyway, I guess we could use it for other cases like for standalone sections (ie ```{% section 'my_section %}```) so that we wouldn't have to declare default content in the YAML header of the page in Wagon.

**Comment by westonganger** [comment]
Yeah you nailed it.

> Anyway, I guess we could use it for other cases like for standalone sections (ie {% section 'my_section %}) so that we wouldn't have to declare default content in the YAML header of the page in Wagon.
