### ISSUE TITLE
wysiwyg text editor for Markdown

### ISSUE THREAD

**Issue by danielmyasnikov** [locomotivecms/engine#903]
LocomotiveCMS seems doesn't have a markdown editor.

Can anyone tell me if I can have a fully featured wysiwyg markdown editor? May be someone already has forked and implemented it. Or at least any help would be appreciated.

**Comment by mremco** [comment]
@did 
Hi Didier,
Is a Markdown powered editor still scheduled for inclusion in 3.0? It's not on the Trello board.
Thanks,
Remco

**Comment by did** [comment]
hi @mremco, now it is :-) https://trello.com/c/wpwmvAs7/62-markdown-editor. Feel free to suggest a markdown editor (light if possible).

**Comment by mremco** [comment]
Thanks @did !
Knowing it would be used by non-tech savvy folks, I believe requirements include:
- instant (split-view) preview
- toolbar, or at least a way to show syntax help (preferable)
- a way to enforce the use of the Markdown editor (disabling the RTF editor).
- Ghost's Markdown editor could serve as inspiration.

https://github.com/OscarGodson/EpicEditor seems to be pretty well-liked all around.
https://github.com/timsayshey/Ghost-Markdown-Editor seems nice and light, but not in very active development.

Cimer !

**Comment by etherbob** [comment]
[uikit's editor](http://getuikit.com/docs/htmleditor.html#markdown) makes good use of [codemirror](http://codemirror.net/)

I've also had good luck with using [ace](http://ace.c9.io/#nav=about) in a similar manner but with JSON

**Comment by brandonmikeska** [comment]
Would something like this work?

http://strapdownjs.com/

**Comment by caiotarifa** [comment]
Have you seem the Ghosditor?

https://github.com/durgesh-priyaranjan/ghosditor
Demo: http://ghosditor.herokuapp.com/

**Comment by did** [comment]
@brandonmikeska, I would prefer a server-side solution if it's possible, otherwise, looks good to me :-)
@caiotarifa very nice editor. Actually, we've got something similar for v3 (except that you can not write in markdown), so I think we will get inspiration from ghosditor (and Ghost), meaning you type in Markdown and you see the result in live.

**Comment by flyeven** [comment]
discourse will use: https://github.com/markdown-it/markdown-it

**Comment by did** [comment]
thanks @flyeven. Does Discourse use nodejs?

**Comment by flyeven** [comment]
no @did, discourse use rails + emberjs , and current uses a pure js editor for markdown parse https://github.com/evilstreak/markdown-js . 

because the lack of table support, will migrate to markdown-it (another js markdown parse and editor):

>.... this is a stopgap until we move to https://github.com/markdown-it/markdown-it7 which does this in a much tidier way.

https://meta.discourse.org/t/markdown-table-support-in-a-discourse-topic/13546/69

**Comment by did** [comment]
that was a very good explanation @flyeven :-)

actually, I found this https://github.com/GitbookIO/kramed which is basically the JS version of the ruby Markdown lib we already use. I should be good with these 2 libs.
